#!/usr/bin/php
<?php
require_once(dirname(__FILE__).'/../configs/defines.php');
require_once(dirname(__FILE__).'/../configs/configure.php');
import(PRELOADER);
import(PREIMPORTS);
import(CORE_DIR.'/DBBuild.class.php');

$build = new DBBuild($argv);
$build->HandleInput();
?>
