#!/usr/bin/php
<?php
require_once(dirname(__FILE__).'/../configs/defines.php');
import(PRELOADER);
import(CORE_DIR.'/Task.class.php');

$task = new Task($argv);
if(isset($argv[1]))
    $task->HandleInput($argv[1]);
else
    echo "No arguments passed... :-/\n";
?>